/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS_PBO;

import static UAS_PBO.Menu.toolscekin;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.JDBCType;
import static java.sql.JDBCType.NULL;
import java.sql.SQLException;
import java.sql.Time;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author asus
 */
public class cek_in extends javax.swing.JFrame {

    /**
     * Creates new form data_pengunjung
     */
    public cek_in() {
        initComponents();
        setLocationRelativeTo(null);
        combobox_relasi();
        tampil_data();
        increment();
        setIconImage();
    }
    

    void tampil_data() {
        koneksi koneksiku = new koneksi();
        koneksiku.koneksi();
        try {
            String sql = "SELECT cek_in.Tgl_cekin, cek_in.Tgl_cekout, cek_in.No_kamar, cek_in.Nama_Tamu, cek_in.Status_kamar, datediff(Tgl_cekout, Tgl_cekin) AS Menginap, cek_in. Total_bayar FROM cek_in";
            koneksiku.rs = koneksiku.st.executeQuery(sql);
            tabel.setModel(DbUtils.resultSetToTableModel(koneksiku.rs));
        } catch (Exception e) {
        }
    }

    void combobox_relasi() {
        koneksi koneksiku = new koneksi();
        koneksiku.koneksi();
        try {
            koneksiku.rs = koneksiku.st.executeQuery("SELECT * FROM persedian_kamar");
            while (koneksiku.rs.next()) {
                nomor.addItem(koneksiku.rs.getString("No_kamar"));
            }

            koneksiku.rs = koneksiku.st.executeQuery("SELECT Nama FROM data_pengujung ORDER BY Nama ASC ");
            while (koneksiku.rs.next()) {
                nama_tamu.addItem(koneksiku.rs.getString("Nama"));
            }
        } catch (Exception e) {
        }
    }

    void hitung_total() {
        koneksi koneksiku = new koneksi();
        koneksiku.koneksi();

        int total;
        try {
            String data = bayar.getText();
            if (data.equals("A") || data.equals("a")) {
                bayar.setText("Masukan Jumlh Hari");
            }
        } catch (Exception e) {
        }
    }

    void increment() {
        koneksi koneksiku = new koneksi();
        koneksiku.koneksi();
        try {
            koneksiku.rs = koneksiku.st.executeQuery("SELECT COUNT(*) FROM cek_in");
            while (koneksiku.rs.next()) {
                int hasil = koneksiku.rs.getInt(1);
                //bayar.setText(""+Integer.toString(a));
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tanggal_cekout = new com.toedter.calendar.JDateChooser();
        nomor = new javax.swing.JComboBox<>();
        nama_tamu = new javax.swing.JComboBox<>();
        bayar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        tgl_cekin = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        k1 = new javax.swing.JComboBox<>();
        k2 = new javax.swing.JTextField();
        Hitung = new javax.swing.JButton();
        rupiah = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Bacground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Check In");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Pristina", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CHECK IN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 240, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 530, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tanggal CekIn");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tanggal Cekout");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nomor");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        simpan.setText("Simpan");
        simpan.setPreferredSize(new java.awt.Dimension(70, 30));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 120, -1));

        edit.setText("Edit");
        edit.setPreferredSize(new java.awt.Dimension(70, 30));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 120, -1));

        hapus.setText("Hapus");
        hapus.setPreferredSize(new java.awt.Dimension(70, 30));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 120, -1));

        clear.setText("Clear");
        clear.setPreferredSize(new java.awt.Dimension(70, 30));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 120, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Total Bayar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nama Tamu");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        tanggal_cekout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tanggal_cekoutMouseClicked(evt);
            }
        });
        tanggal_cekout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tanggal_cekoutKeyReleased(evt);
            }
        });
        getContentPane().add(tanggal_cekout, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 240, -1));

        nomor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));
        getContentPane().add(nomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 240, -1));

        nama_tamu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));
        getContentPane().add(nama_tamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 240, -1));

        bayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bayarMouseClicked(evt);
            }
        });
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bayarKeyReleased(evt);
            }
        });
        getContentPane().add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 240, -1));

        tabel.setBackground(new java.awt.Color(255, 153, 0));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 610, 250));
        getContentPane().add(tgl_cekin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 240, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/close_14776.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 130, 130));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KALKULATOR");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        k1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blok Kamar", "A", "B", "C" }));
        jPanel2.add(k1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, -1));

        k2.setText("Lama Menginap?");
        k2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                k2MouseClicked(evt);
            }
        });
        jPanel2.add(k2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, -1));

        Hitung.setText("HITUNG");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel2.add(Hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, -1));

        rupiah.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rupiah.setText("0");
        rupiah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rupiahKeyReleased(evt);
            }
        });
        jPanel2.add(rupiah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 120, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText(" Rp.");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 40, 30));

        jSeparator1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 170, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 170, 160));

        Bacground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/5169fc28544fde43c93d741341a25f00.jpg"))); // NOI18N
        getContentPane().add(Bacground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 1020, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        koneksi koneksiku = new koneksi();
        koneksiku.koneksi();

        SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = String.valueOf(fm.format(tgl_cekin.getDate()));
        String tanggalku = String.valueOf(fm.format(tanggal_cekout.getDate()));

        String status_kmr = "PENUH";
        int hasil, jumlah = 0;
        try {

            koneksiku.st.executeUpdate("ALTER TABLE cek_in DROP No");
            koneksiku.st.executeUpdate("ALTER TABLE cek_in ADD No INT(10) NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (No)");

            koneksiku.rs = koneksiku.st.executeQuery("SELECT COUNT(*) FROM cek_in");
            while (koneksiku.rs.next()) {
                hasil = koneksiku.rs.getInt(1);
                // jumlah=(""+Integer.toString(hasil+1));
                jumlah = hasil + 1;
            }

            if (bayar.getText().equals("")) {
                bayar.setText("Kolom Tidak Boleh Kosong");
                JOptionPane.showMessageDialog(null, "Kolom Tidak Boleh Kosong");
            }
            koneksiku.st.executeUpdate("INSERT INTO cek_in VALUES ('" + jumlah + "','" + tanggal + "','" + tanggalku + "','" + nomor.getSelectedItem() + "','" + nama_tamu.getSelectedItem() + "','" + bayar.getText() + "','" + status_kmr + "')");

            koneksiku.st.executeUpdate("UPDATE persedian_kamar SET Status_kamar='PENUH' WHERE No_kamar='" + nomor.getSelectedItem() + "' ");
            tampil_data();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_simpanActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        int harga;
        int baris = tabel.rowAtPoint(evt.getPoint());

        String tgl_cekin = tabel.getValueAt(baris, 0).toString();
        java.util.Date date2 = null;
        try {
            date2 = new SimpleDateFormat("yyyy-MM-dd").parse(tgl_cekin);
        } catch (Exception e) {
        }
        this.tgl_cekin.setDate(date2);

        String tgl_out = tabel.getValueAt(baris, 1).toString();
        java.util.Date date1 = null;
        try {
            date1 = new SimpleDateFormat("yyyy-MM-dd").parse(tgl_out);
        } catch (Exception e) {
        }
        tanggal_cekout.setDate(date1);

        String nomork = tabel.getValueAt(baris, 2).toString();
        nomor.setSelectedItem(nomork);

        String nama = tabel.getValueAt(baris, 3).toString();
        nama_tamu.setSelectedItem(nama);

        String byar = tabel.getValueAt(baris, 6).toString();
        bayar.setText(byar);
    }//GEN-LAST:event_tabelMouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        koneksi koneksiku = new koneksi();
        koneksiku.koneksi();

        SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = String.valueOf(fm.format(tgl_cekin.getDate()));
        try {
            koneksiku.st.executeUpdate("DELETE FROM `cek_in` WHERE Tgl_cekin='" + tanggal + "' AND Nama_Tamu='" + nama_tamu.getSelectedItem() + "'");
            clearActionPerformed(evt);
            tampil_data();
        } catch (Exception e) {
            System.out.println("Gagal :" + e);
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        koneksi koneksiku = new koneksi();
        koneksiku.koneksi();

        SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = String.valueOf(fm.format(tgl_cekin.getDate()));
        String tanggalku = String.valueOf(fm.format(tanggal_cekout.getDate()));
        try {
            koneksiku.st.executeUpdate("UPDATE cek_in SET Tgl_cekin='" + tanggal + "', Tgl_cekout='" + tanggalku + "', No_kamar='" + nomor.getSelectedItem() + "', Nama_Tamu='" + nama_tamu.getSelectedItem() + "', Total_bayar='" + bayar.getText() + "', Status_kamar='PENUH' WHERE Nama_Tamu='" + nama_tamu.getSelectedItem() + "' AND Tgl_cekin='" + tanggal + "'");
            koneksiku.st.executeUpdate("UPDATE persedian_kamar SET Status_kamar='PENUH' WHERE No_kamar='"+nomor.getSelectedItem()+"'");
            tampil_data();
        } catch (Exception e) {
            System.out.println("gagal " + e);
        }
    }//GEN-LAST:event_editActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        tgl_cekin.setDate(null);
        tanggal_cekout.setDate(null);
        nomor.setSelectedItem("Pilih");
        nama_tamu.setSelectedItem("Pilih");
        bayar.setText("");
        k1.setSelectedItem("Blok Kamar");
        k2.setText("Lama Menginap?");
        rupiah.setText("0");
        
        tampil_data();
    }//GEN-LAST:event_clearActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void tanggal_cekoutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tanggal_cekoutKeyReleased


    }//GEN-LAST:event_tanggal_cekoutKeyReleased

    private void bayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bayarMouseClicked
        bayar.setText("");
    }//GEN-LAST:event_bayarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        toolscekin.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tanggal_cekoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanggal_cekoutMouseClicked
        
    }//GEN-LAST:event_tanggal_cekoutMouseClicked

    private void k2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_k2MouseClicked
        k2.setText("");
    }//GEN-LAST:event_k2MouseClicked

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        int lama;
        try {
            String blokkmr = (String) k1.getSelectedItem();
            lama = Integer.parseInt(k2.getText());
            if (blokkmr.equals("A")) {
                int data = 150000 * lama;

                double ganti = Double.valueOf(data);
                DecimalFormat df = new DecimalFormat("#,###,##0");
                bayar.setText(df.format(ganti));
                rupiah.setText(df.format(data));
            }

            if (blokkmr.equals("B")) {
                int data = 100000 * lama;
                rupiah.setText(Integer.toString(data));
                bayar.setText(Integer.toString(data));

                double ganti = Double.valueOf(data);
                DecimalFormat df = new DecimalFormat("#,###,##0");
                bayar.setText(df.format(ganti));
                rupiah.setText(df.format(data));

            }

            if (blokkmr.equals("C")) {
                int data = 50000 * lama;
                rupiah.setText(Integer.toString(data));
                bayar.setText(Integer.toString(data));

                double ganti = Double.valueOf(data);
                DecimalFormat df = new DecimalFormat("#,###,##0");
                bayar.setText(df.format(ganti));
                rupiah.setText(df.format(data));

            }
            if (blokkmr.equals("Blok Kamar")) {
                JOptionPane.showMessageDialog(null, "Tidak Dimengeri, \n Pastiakn Memilih #BLOK KAMAR yang Benar");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_HitungActionPerformed

    private void rupiahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rupiahKeyReleased
        String angka = rupiah.getText().replaceAll("\\", "");
        double ganti = Double.valueOf(angka);
        DecimalFormat df = new DecimalFormat("#,###,##0");
        rupiah.setText(df.format(ganti));
    }//GEN-LAST:event_rupiahKeyReleased

    private void bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyReleased
        try {
            String angka = bayar.getText().replaceAll("\\,", "");
            double ganti = Double.valueOf(angka);
            DecimalFormat df = new DecimalFormat("#,###,##0");
            bayar.setText(df.format(ganti));

        } catch (Exception e) {
        }

    }//GEN-LAST:event_bayarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cek_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cek_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cek_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cek_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cek_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bacground;
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField bayar;
    private javax.swing.JButton clear;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> k1;
    private javax.swing.JTextField k2;
    private javax.swing.JComboBox<String> nama_tamu;
    private javax.swing.JComboBox<String> nomor;
    private javax.swing.JLabel rupiah;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private com.toedter.calendar.JDateChooser tanggal_cekout;
    private com.toedter.calendar.JDateChooser tgl_cekin;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("garuda_indonesin_artwork_illustration_generated.jpg")));
    }
}
