/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS_PBO;

import static UAS_PBO.Menu.toolscekin;
import static UAS_PBO.Menu.toolscekout;
import java.text.SimpleDateFormat;
import javax.print.DocFlavor;
import net.proteanit.sql.DbUtils;
import UAS_PBO.cek_in;
import java.awt.Toolkit;
import java.util.Date;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author asus
 */
public class cekout extends javax.swing.JFrame {

    /**
     * Creates new form data_pengunjung
     */
    public cekout() {
        initComponents();
        setLocationRelativeTo(null);
        tampil_data();
        edit.setEnabled(false);
        setIconImage();
    }
    
    void tampil_data(){
        koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        try {
            String sql="SELECT cek_in.Tgl_cekin, cek_in.Tgl_cekout,cek_in.Nama_Tamu,cek_in.Total_bayar AS Status_Bayar,cek_in.No_kamar,cek_in.Status_kamar FROM cek_in";
            koneksiku.rs=koneksiku.st.executeQuery(sql);
            tabel.setModel(DbUtils.resultSetToTableModel(koneksiku.rs));
        } catch (Exception e) {
        }
    }
    
    void update(){
        koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        
        SimpleDateFormat fm=new SimpleDateFormat("yyyy-MM-dd");
        String tanggal=String.valueOf(fm.format(tgl_cekout.getDate()));
        
        try {
            koneksiku.st.executeUpdate("UPDATE cek_in SET Status_kamar='"+status_kamar.getSelectedItem()+"' WHERE No_kamar='"+nomorkmr.getText()+"' And Tgl_cekout='"+tanggal+"'");
             koneksiku.st.executeUpdate("UPDATE persedian_kamar SET Status_kamar='"+status_kamar.getSelectedItem() +"' WHERE No_kamar='"+nomorkmr.getText()+"'");
            tampil_data();
        } catch (Exception e) {
            System.out.println("Gagal : "+e);
        }
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tgl_cekout = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        status_byr = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        status_kamar = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        nama = new javax.swing.JTextField();
        nomorkmr = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        print = new javax.swing.JButton();
        Bacground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Check OUT");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Pristina", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CHECK OUT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 300, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 530, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tanggal Cekout");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        tgl_cekout.setDateFormatString("MMM dd, yyyy");
        getContentPane().add(tgl_cekout, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 240, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nama Tamu");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Status Bayar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        status_byr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunas", "-" }));
        getContentPane().add(status_byr, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 240, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nomor Kamar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        status_kamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kosong" }));
        getContentPane().add(status_kamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 240, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Status Kamar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        simpan.setText("Simpan");
        simpan.setPreferredSize(new java.awt.Dimension(70, 30));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 120, -1));

        edit.setText("Edit");
        edit.setPreferredSize(new java.awt.Dimension(70, 30));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 120, -1));

        jButton1.setText("Hapus");
        jButton1.setPreferredSize(new java.awt.Dimension(70, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 120, -1));

        jButton3.setText("Clear");
        jButton3.setPreferredSize(new java.awt.Dimension(70, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 120, -1));

        tabel.setBackground(new java.awt.Color(255, 153, 0));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 610, 250));

        nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                namaKeyReleased(evt);
            }
        });
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 240, -1));
        getContentPane().add(nomorkmr, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 240, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/close_14776.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 130, 130));

        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/icons8-print-48.png"))); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 110, 50));

        Bacground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/5169fc28544fde43c93d741341a25f00.jpg"))); // NOI18N
        getContentPane().add(Bacground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 1020, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        SimpleDateFormat fm=new SimpleDateFormat("yyyy-MM-dd");
        String tanggal=String.valueOf(fm.format(tgl_cekout.getDate()));
        try {
            koneksiku.st.executeUpdate("INSERT INTO cek_out VALUE ('"+tanggal+"', '"+nama.getText()+"', '"+status_byr.getSelectedItem()+"', '"+nomorkmr.getText()+"', '"+status_kamar.getSelectedItem()+"')");
            update();
        } catch (Exception e) {
            System.out.println("Gagal : "+e);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        int baris=tabel.rowAtPoint(evt.getPoint());
        
        String cekout=tabel.getValueAt(baris, 1).toString();
        java.util.Date date = null;
        try {
            date = new SimpleDateFormat("yyyy-MM-dd").parse(cekout);
        } catch (Exception e) {
        }
        tgl_cekout.setDate(date);
        
        String tamu=tabel.getValueAt(baris, 2).toString();
        nama.setText(tamu);
        
        String status_bayar=tabel.getValueAt(baris, 3).toString();
        status_byr.setSelectedItem(status_bayar);
        
        String nomor=tabel.getValueAt(baris, 4).toString();
        nomorkmr.setText(nomor);
    }//GEN-LAST:event_tabelMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        try {
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_editActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
        toolscekout.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        SimpleDateFormat fm=new SimpleDateFormat("yyyy-MM-dd");
        String tanggal=String.valueOf(fm.format(tgl_cekout.getDate()));
        try {
            koneksiku.st.executeUpdate("DELETE FROM cek_in WHERE Tgl_cekout='"+tanggal+"' AND Nama_Tamu='"+nama.getText()+"'");
            tampil_data();
        } catch (Exception e) {
            System.out.println("Gagal : "+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tgl_cekout.setDate(null);
        nama.setText("");
        status_byr.setSelectedItem("");
        nomorkmr.setText("");
        status_kamar.setSelectedItem("");
        tampil_data();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        
        try {
            String report=("C:\\Users\\asus\\Downloads\\Ricky_2B_P1_PBO\\src\\UAS_PBO\\nota.jrxml");
            HashMap hash=new HashMap();
            hash.put("tanggal", tgl_cekout.getDate());
            hash.put("kamar", nomorkmr.getText());
            hash.put("Nama", login.User.getText());
            
            JasperReport JRpt=JasperCompileManager.compileReport(report);
            JasperPrint jpprint=JasperFillManager.fillReport(JRpt, hash, koneksiku.con);
           JasperViewer.viewReport(jpprint, false);
        } catch (Exception e) {
            System.out.println("gagal :"+e);
        }
    }//GEN-LAST:event_printActionPerformed

    private void namaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaKeyReleased
        String cari=nama.getText();
        koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        try {
            String sql="SELECT cek_in.Tgl_cekin, cek_in.Tgl_cekout,cek_in.Nama_Tamu,cek_in.Total_bayar AS Status_Bayar,cek_in.No_kamar,cek_in.Status_kamar FROM cek_in WHERE Nama_Tamu LIKE '%"+cari+"%'";
            koneksiku.rs=koneksiku.st.executeQuery(sql);
            tabel.setModel(DbUtils.resultSetToTableModel(koneksiku.rs));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_namaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cekout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cekout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cekout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cekout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cekout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bacground;
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nomorkmr;
    private javax.swing.JButton print;
    private javax.swing.JButton simpan;
    private javax.swing.JComboBox<String> status_byr;
    private javax.swing.JComboBox<String> status_kamar;
    private javax.swing.JTable tabel;
    private com.toedter.calendar.JDateChooser tgl_cekout;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("garuda_indonesin_artwork_illustration_generated.jpg")));
    }
}
