/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS_PBO;

import com.mysql.jdbc.log.NullLogger;
//import com.sun.xml.internal.fastinfoset.EncodingConstants;
import java.awt.Toolkit;
import java.sql.JDBCType;
import static java.sql.JDBCType.NULL;
import javafx.fxml.FXMLLoader;
import javax.swing.JOptionPane;
import javax.swing.text.html.HTML;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author asus
 */
public class data_pengunjung extends javax.swing.JFrame {

    /**
     * Creates new form data_pengunjung
     */
    public data_pengunjung() {
        initComponents();
        setLocationRelativeTo(null);
        tampildata();
        setIconImage();
    }
    
    void tampildata(){
        koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        try {
            koneksiku.rs=koneksiku.st.executeQuery("SELECT No_Ktp, Nama, Alamat, jenis_kelamin FROM data_pengujung");
            tabel.setModel(DbUtils.resultSetToTableModel(koneksiku.rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println("gagal :"+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ktp = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        pria = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        bacground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Pengunjung");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Pristina", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA PENGUNJUNG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 490, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 530, 70));

        tabel.setBackground(new java.awt.Color(255, 153, 0));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        tabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tabelKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 610, 250));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("No KTP");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        ktp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ktpKeyReleased(evt);
            }
        });
        getContentPane().add(ktp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 220, -1));

        nama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                namaMouseClicked(evt);
            }
        });
        nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                namaKeyReleased(evt);
            }
        });
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 220, -1));
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 220, -1));

        hapus.setText("Hapus");
        hapus.setPreferredSize(new java.awt.Dimension(70, 30));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 120, -1));

        edit.setText("Edit");
        edit.setPreferredSize(new java.awt.Dimension(70, 30));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 120, -1));

        clear.setText("Clear");
        clear.setPreferredSize(new java.awt.Dimension(70, 30));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 120, -1));

        simpan.setText("Simpan");
        simpan.setPreferredSize(new java.awt.Dimension(70, 30));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 120, -1));

        buttonGroup1.add(pria);
        pria.setText("Laki-laki");
        getContentPane().add(pria, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 100, -1));

        buttonGroup1.add(perempuan);
        perempuan.setText("Perempuan");
        getContentPane().add(perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 110, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/close_14776.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 130, 130));

        bacground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/5169fc28544fde43c93d741341a25f00.jpg"))); // NOI18N
        getContentPane().add(bacground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 1020, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        
        String jk;
        if (pria.isSelected()) {
            jk=pria.getText();
        }else{
            jk=perempuan.getText();
        }
         
        try {
            koneksiku.st.executeUpdate("insert into data_pengujung value ("
                                     + "'"+ktp.getText()+"', "
                                     + "'"+nama.getText()+"', "
                                     + "'"+alamat.getText()+"', "
                                     + "'"+jk+"', User='"+NULL+"', '')");
            JOptionPane.showMessageDialog(null, "Berhasil di Simpan");
            tampildata();
            clearActionPerformed(evt);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal di Simpan");
            System.out.println("Gagal : "+e);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        ktp.setText("");
        nama.setText("");
        alamat.setText("");
        buttonGroup1.clearSelection();
        tampildata();
    }//GEN-LAST:event_clearActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        
         String jk;
        if (pria.isSelected()) {
            jk=pria.getText();
        }else{
            jk=perempuan.getText();
        }
        
        try {
            koneksiku.st.executeUpdate("UPDATE data_pengujung SET "
                                     + "No_Ktp='"+ktp.getText()+"', "
                                     + "Nama='"+nama.getText()+"',"
                                     + "Alamat='"+alamat.getText()+"', "
                                     + "jenis_kelamin='"+jk+"', "
                                     + "User = NULL "
                                     + "WHERE No_Ktp='"+ktp.getText()+"'");
            tampildata();
        } catch (Exception e) {
            System.out.println("Gagal : "+e);
        }
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        try {
            koneksiku.st.executeUpdate("DELETE FROM data_pengujung WHERE No_Ktp='"+ktp.getText()+"'");
            tampildata();
        } catch (Exception e) {
        }
        
        clearActionPerformed(evt);
    }//GEN-LAST:event_hapusActionPerformed

    private void ktpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ktpKeyReleased
        String cari=ktp.getText();
        koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        try {
            String sql="SELECT No_Ktp, Nama, Alamat, jenis_kelamin FROM data_pengujung WHERE No_Ktp LIKE '%"+cari+"%'";
            koneksiku.rs=koneksiku.st.executeQuery(sql);
            tabel.setModel(DbUtils.resultSetToTableModel(koneksiku.rs));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_ktpKeyReleased

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        int baris=tabel.rowAtPoint(evt.getPoint());
        
        String data_ktp=tabel.getValueAt(baris, 0).toString();
        ktp.setText(data_ktp);
        
        String data_nama=tabel.getValueAt(baris, 1).toString();
        nama.setText(data_nama);
        
        String data_alamat=tabel.getValueAt(baris, 2).toString();
        alamat.setText(data_alamat);
        
        String data_jk=tabel.getValueAt(baris, 3).toString();
        if (data_jk.equals("Laki-laki")) {
            pria.setSelected(true);
        }else if (data_jk.equals("Perempuan")) {
            perempuan.setSelected(true);
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void namaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaKeyReleased
        String cari=nama.getText();
        koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        try {
            String sql="SELECT No_Ktp, Nama, Alamat, jenis_kelamin FROM data_pengujung WHERE Nama LIKE '%"+cari+"%'";
            koneksiku.rs=koneksiku.st.executeQuery(sql);
            tabel.setModel(DbUtils.resultSetToTableModel(koneksiku.rs));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_namaKeyReleased

    private void tabelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelKeyReleased

    }//GEN-LAST:event_tabelKeyReleased

    private void tabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelKeyPressed

    private void tabelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
         Menu.toospengunjung.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void namaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaMouseClicked

    }//GEN-LAST:event_namaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_pengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_pengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_pengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_pengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_pengunjung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel bacground;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ktp;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JRadioButton pria;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("garuda_indonesin_artwork_illustration_generated.jpg")));
    }
}
