/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS_PBO;


import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setIcon(); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dekstop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        LOGIN = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exit = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jatayu Hotel");

        dekstop.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dekstopLayout = new javax.swing.GroupLayout(dekstop);
        dekstop.setLayout(dekstopLayout);
        dekstopLayout.setHorizontalGroup(
            dekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        dekstopLayout.setVerticalGroup(
            dekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 30));

        LOGIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/user(1).png"))); // NOI18N
        LOGIN.setText("LOGIN");

        menulogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menulogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/password.png"))); // NOI18N
        menulogin.setText("LOGIN");
        menulogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuloginActionPerformed(evt);
            }
        });
        LOGIN.add(menulogin);

        menulogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menulogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/refresh_update_icon_142975.png"))); // NOI18N
        menulogout.setText("LOGOUT");
        menulogout.setEnabled(false);
        menulogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menulogoutMouseClicked(evt);
            }
        });
        menulogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menulogoutActionPerformed(evt);
            }
        });
        LOGIN.add(menulogout);
        LOGIN.add(jSeparator1);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/power-on.png"))); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        LOGIN.add(exit);

        jMenuBar1.add(LOGIN);

        tools.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/tool-box-icon.png"))); // NOI18N
        tools.setText("TOOLS");
        tools.setEnabled(false);
        tools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolsActionPerformed(evt);
            }
        });

        toospengunjung.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, 0));
        toospengunjung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/staff-symbol.png"))); // NOI18N
        toospengunjung.setText("Data Pengunjung");
        toospengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toospengunjungActionPerformed(evt);
            }
        });
        tools.add(toospengunjung);

        toolskamar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, 0));
        toolskamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/sleepingbedsilhouette_89127.png"))); // NOI18N
        toolskamar.setText("Data Kamar");
        toolskamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolskamarActionPerformed(evt);
            }
        });
        tools.add(toolskamar);

        toolscekin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, 0));
        toolscekin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/pencil-writing-on-a-paper-sheet_icon-icons.com_70422.png"))); // NOI18N
        toolscekin.setText("Cek IN");
        toolscekin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolscekinActionPerformed(evt);
            }
        });
        tools.add(toolscekin);

        toolscekout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, 0));
        toolscekout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/checkmark.png"))); // NOI18N
        toolscekout.setText("Cek OUT");
        toolscekout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolscekoutActionPerformed(evt);
            }
        });
        tools.add(toolscekout);

        toolsinfokamar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, 0));
        toolsinfokamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/icons8-checklist-32.png"))); // NOI18N
        toolsinfokamar.setText("Informasi Kamar");
        toolsinfokamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolsinfokamarActionPerformed(evt);
            }
        });
        tools.add(toolsinfokamar);

        jMenuBar1.add(tools);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/help(1).png"))); // NOI18N
        jMenu5.setText("Help");
        jMenu5.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenu5AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        toolscmd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        toolscmd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/icons8-console-32.png"))); // NOI18N
        toolscmd.setText("Cmd");
        toolscmd.setEnabled(false);
        toolscmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolscmdActionPerformed(evt);
            }
        });
        jMenu5.add(toolscmd);

        reset.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/reset(1).png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jMenu5.add(reset);

        inpo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        inpo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/info.png"))); // NOI18N
        inpo.setText("Info Aplikasi");
        inpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpoActionPerformed(evt);
            }
        });
        jMenu5.add(inpo);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dekstop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dekstop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuloginActionPerformed
        try {
        dekstop.removeAll();
        login loginku =new login();
        loginku.setVisible(true);
        dekstop.add(loginku);
        menulogin.setVisible(false);
        } catch (Exception e) {
        } 
    }//GEN-LAST:event_menuloginActionPerformed

    private void menulogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menulogoutActionPerformed
        int pilih=JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Akan LOGOUT ?", null, JOptionPane.OK_OPTION);
        if(pilih==JOptionPane.OK_OPTION){
            JOptionPane.showMessageDialog(null, "Berhasil LOGOUT");
            menulogin.setEnabled(true);
            tools.setEnabled(false);
            menulogout.setEnabled(false);
            toolscmd.setEnabled(false);
        }else{
        JOptionPane.getRootFrame();
         menulogout.setEnabled(true);
        }
    }//GEN-LAST:event_menulogoutActionPerformed

    private void toolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolsActionPerformed
        
    }//GEN-LAST:event_toolsActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        int pilih=JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Keluar", null, JOptionPane.OK_OPTION);
          if(pilih==JOptionPane.OK_OPTION){
            System.exit(0);
        }else{
        JOptionPane.getRootFrame();
        }
    }//GEN-LAST:event_exitActionPerformed

    private void toospengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toospengunjungActionPerformed
         data_pengunjung pengunjung=new data_pengunjung();
        pengunjung.setVisible(true);
        Menu.toospengunjung.setEnabled(false);
        
    }//GEN-LAST:event_toospengunjungActionPerformed

    private void menulogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulogoutMouseClicked

    }//GEN-LAST:event_menulogoutMouseClicked

    private void toolskamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolskamarActionPerformed
        persedian_kamar kamar=new persedian_kamar();
        kamar.setVisible(true);
        toolskamar.setEnabled(false);
    }//GEN-LAST:event_toolskamarActionPerformed

    private void toolscekinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolscekinActionPerformed
        cek_in cekin=new cek_in();
        cekin.setVisible(true);
        toolscekin.setEnabled(false);
    }//GEN-LAST:event_toolscekinActionPerformed

    private void toolscekoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolscekoutActionPerformed
        cekout cekout=new cekout();
        cekout.setVisible(true);
        toolscekout.setEnabled(false);
    }//GEN-LAST:event_toolscekoutActionPerformed

    private void toolsinfokamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolsinfokamarActionPerformed
       informasi_kamar infokamar=new informasi_kamar();
        infokamar.setVisible(true);
        toolsinfokamar.setEnabled(false);
    }//GEN-LAST:event_toolsinfokamarActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
    
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenu5AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenu5AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5AncestorAdded

    private void inpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpoActionPerformed
        help helpku=new help();
        helpku.setVisible(true);
        inpo.setEnabled(false);
    }//GEN-LAST:event_inpoActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        try {
          int pilih=JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Akan Reset Ke default", null, JOptionPane.OK_OPTION);
          if(pilih==JOptionPane.OK_OPTION){
              koneksiku.st.executeUpdate("INSERT INTO data_pengujung VALUES ('111','Admin Jatayu','Root','Root','Admin','123')");
              JOptionPane.showMessageDialog(null, "Data Login Sukses kembali ke default");
        }else{
        JOptionPane.getRootFrame();
        }
        } catch (Exception e) {
            System.out.println("gagal"+e);
            JOptionPane.showMessageDialog(null, "Data default sudah Tersedia Silahkan Login kembali");
        }
    }//GEN-LAST:event_resetActionPerformed

    private void toolscmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolscmdActionPerformed
        new cmd().setVisible(true);
    }//GEN-LAST:event_toolscmdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu LOGIN;
    private javax.swing.JDesktopPane dekstop;
    private javax.swing.JMenuItem exit;
    public static final javax.swing.JMenuItem inpo = new javax.swing.JMenuItem();
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public static final javax.swing.JMenuItem menulogin = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem menulogout = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem reset = new javax.swing.JMenuItem();
    public static final javax.swing.JMenu tools = new javax.swing.JMenu();
    public static final javax.swing.JMenuItem toolscekin = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem toolscekout = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem toolscmd = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem toolsinfokamar = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem toolskamar = new javax.swing.JMenuItem();
    public static final javax.swing.JMenuItem toospengunjung = new javax.swing.JMenuItem();
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("garuda_indonesin_artwork_illustration_generated.jpg")));
    }
}
