/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS_PBO;

import static UAS_PBO.Menu.toolskamar;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author asus
 */
public class persedian_kamar extends javax.swing.JFrame {

    /**
     * Creates new form data_pengunjung
     */
    public persedian_kamar() {
        initComponents();
        setLocationRelativeTo(null);
        tampil_data();
        setIconImage();
    }
    
    void tampil_data(){
        koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        try {
            String sql="SELECT * FROM persedian_kamar";
            koneksiku.rs=koneksiku.st.executeQuery(sql);
            tabel.setModel(DbUtils.resultSetToTableModel(koneksiku.rs));
        } catch (Exception e) {
        }
    }
    
    void format_rupiah(){
        try {
             String angka=menengah.getText().replaceAll("\\,", "");
             double ganti=Double.valueOf(angka);
             DecimalFormat df=new DecimalFormat("#,###,##0");
             menengah.setText(df.format(ganti));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }     
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomor = new javax.swing.JTextField();
        kebawah = new javax.swing.JRadioButton();
        menengah = new javax.swing.JRadioButton();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        blok_kamar = new javax.swing.JComboBox<>();
        statuskamar = new javax.swing.JComboBox<>();
        keatas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Bacground = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Kamar");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Pristina", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA KAMAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 430, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 530, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Blok Kamar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nomor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Status Kamar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Harga / Malam");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        nomor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomorKeyReleased(evt);
            }
        });
        getContentPane().add(nomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 240, -1));

        buttonGroup1.add(kebawah);
        kebawah.setText("50,000");
        getContentPane().add(kebawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 80, -1));

        buttonGroup1.add(menengah);
        menengah.setText("100,000");
        menengah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                menengahKeyReleased(evt);
            }
        });
        getContentPane().add(menengah, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 80, -1));

        simpan.setText("Simpan");
        simpan.setPreferredSize(new java.awt.Dimension(70, 30));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 120, -1));

        edit.setText("Edit");
        edit.setPreferredSize(new java.awt.Dimension(70, 30));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 120, -1));

        hapus.setText("Hapus");
        hapus.setPreferredSize(new java.awt.Dimension(70, 30));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 120, -1));

        clear.setText("Clear");
        clear.setPreferredSize(new java.awt.Dimension(70, 30));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 120, -1));

        blok_kamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "A", "B", "C" }));
        getContentPane().add(blok_kamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 240, -1));

        statuskamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kosong", "Penuh" }));
        getContentPane().add(statuskamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 240, -1));

        buttonGroup1.add(keatas);
        keatas.setText("150,000");
        keatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keatasActionPerformed(evt);
            }
        });
        getContentPane().add(keatas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        tabel.setBackground(new java.awt.Color(255, 153, 0));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        tabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 610, 250));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/close_14776.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 130, 130));

        Bacground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_PBO/5169fc28544fde43c93d741341a25f00.jpg"))); // NOI18N
        getContentPane().add(Bacground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 1020, 630));

        jCheckBox1.setText("jCheckBox1");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        
        String jk;
        if(kebawah.isSelected()){
            jk=kebawah.getText();
        }
        
        else{
            jk=menengah.getText();
        }
        
        if(keatas.isSelected()){
            jk=keatas.getText();
        }
        try {
            koneksiku.st.executeUpdate("INSERT INTO persedian_kamar VALUE ("
                                     + "'"+blok_kamar.getSelectedItem()+"','"
                                     + ""+nomor.getText()+"','"
                                     + ""+statuskamar.getSelectedItem()+"', '"
                                     + ""+jk+"')");
            tampil_data();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void keatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keatasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keatasActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        
        String jk;
        if(kebawah.isSelected()){
            jk=kebawah.getText();
        }else{
            jk=menengah.getText();
        }
        if (keatas.isSelected()){
            jk=keatas.getText();
        }
        
        try {
            koneksiku.st.executeUpdate("UPDATE persedian_kamar SET Blok_kamar='"+blok_kamar.getSelectedItem()+"', No_kamar='"+nomor.getText()+"',Status_kamar='"+statuskamar.getSelectedItem()+"',Harga='"+jk+"' WHERE No_kamar='"+nomor.getText()+"'");
            tampil_data();
        } catch (Exception e) {
            System.out.println("Gagal"+e);
        }
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
         koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        try {
            koneksiku.st.executeUpdate("DELETE FROM persedian_kamar WHERE No_kamar='"+nomor.getText()+"'");
            tampil_data();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       blok_kamar.setSelectedItem("Pilih");
       nomor.setText("");
       statuskamar.setSelectedItem("Kosong");
       buttonGroup1.clearSelection();
       
       tampil_data();
    }//GEN-LAST:event_clearActionPerformed

    private void tabelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelKeyReleased

    }//GEN-LAST:event_tabelKeyReleased

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        int baris=tabel.rowAtPoint(evt.getPoint());
        
        String b=tabel.getValueAt(baris, 0).toString(); 
        blok_kamar.setSelectedItem(b);
        
        String no=tabel.getValueAt(baris, 1).toString();
        nomor.setText(no); 
        
        String status=tabel.getValueAt(baris, 2).toString();
        statuskamar.setSelectedItem(status);
        
        String radio=tabel.getValueAt(baris, 3).toString();
        if (radio.equals("150,000")) {
            keatas.setSelected(true);
        }else if (radio.equals("100,000")) {
            menengah.setSelected(true);
        }if (radio.equals("50,000")) {
            kebawah.setSelected(true);
        }
        format_rupiah();
    }//GEN-LAST:event_tabelMouseClicked

    private void nomorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomorKeyReleased
        koneksi koneksiku=new koneksi();
        koneksiku.koneksi();
        try {
            koneksiku.rs=koneksiku.st.executeQuery("SELECT * FROM persedian_kamar WHERE No_kamar LIKE '%"+nomor.getText()+"%'");
            tabel.setModel(DbUtils.resultSetToTableModel(koneksiku.rs));
        } catch (Exception e) {
            System.out.println("Error :"+e);
        }
    }//GEN-LAST:event_nomorKeyReleased

    private void menengahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menengahKeyReleased

    }//GEN-LAST:event_menengahKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        toolskamar.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(persedian_kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(persedian_kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(persedian_kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(persedian_kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new persedian_kamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bacground;
    private javax.swing.JComboBox<String> blok_kamar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton keatas;
    private javax.swing.JRadioButton kebawah;
    private javax.swing.JRadioButton menengah;
    private javax.swing.JTextField nomor;
    private javax.swing.JButton simpan;
    private javax.swing.JComboBox<String> statuskamar;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("garuda_indonesin_artwork_illustration_generated.jpg")));
    }
}
